export const assessments = [
  {
    title: "Treatment Modalities & Basic Principles",
    subtitle: "Module-End Quiz",
    avgScore: 93,
    avgTimeSpent: "5m",
    avgAttempts: 1,
    status: "Active",
    lastUpdated: "Apr 15, 2025",
  },
  {
    title: "Treatment Modalities & Basic Principles",
    subtitle: "Final Comprehensive Assessment",
    avgScore: 67,
    avgTimeSpent: "12m",
    avgAttempts: 1,
    status: "Active",
    lastUpdated: "Apr 14, 2025",
  },
  {
    title: "Physiotherapy Fundamentals",
    subtitle: "Final Comprehensive Assessment",
    avgScore: 29,
    avgTimeSpent: "6m",
    avgAttempts: 1,
    status: "Active",
    lastUpdated: "Apr 13, 2025",
  },
  {
    title: "Rehab & Conditioning Training",
    subtitle: "Exercise Selection Quiz",
    avgScore: 73,
    avgTimeSpent: "12m",
    avgAttempts: 2,
    status: "Active",
    lastUpdated: "Apr 12, 2025",
  },
  {
    title: "Rehab & Conditioning Training",
    subtitle: "Final Assessment",
    avgScore: 35,
    avgTimeSpent: "3m",
    avgAttempts: 2,
    status: "Active",
    lastUpdated: "Apr 11, 2025",
  },
  {
    title: "Clinical Pilates Principles",
    subtitle: "Principles & Alignment Quiz",
    avgScore: 90,
    avgTimeSpent: "10m",
    avgAttempts: 1,
    status: "Active",
    lastUpdated: "Apr 10, 2025",
  },
  {
    title: "Clinical Pilates Principles",
    subtitle: "Final Assessment",
    avgScore: 93,
    avgTimeSpent: "15m",
    avgAttempts: 1,
    status: "Active",
    lastUpdated: "Apr 9, 2025",
  },
];
